# Generated by Django 5.2.4 on 2025-07-18 17:59

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do cupom que o usuário vai digitar', max_length=50, unique=True)),
                ('desconto_percentual', models.IntegerField(blank=True, help_text='Desconto em porcentagem (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('desconto_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Desconto em valor fixo (R$)', max_digits=10, null=True)),
                ('valido_de', models.DateTimeField(default=django.utils.timezone.now)),
                ('valido_ate', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('uso_maximo', models.IntegerField(default=100, help_text='Número máximo de vezes que o cupom pode ser usado')),
                ('uso_atual', models.IntegerField(default=0)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor mínimo do pedido para aplicar o cupom', max_digits=10)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-id'],
            },
        ),
    ]
