# Generated by Django 5.2.4 on 2025-07-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pagamento pendente'), ('F', 'Falha no Pagamento'), ('P', 'Processando'), ('R', 'Reembolsado'), ('C', 'Concluido'), ('C', 'Cancelado'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1),
        ),
    ]
