# Generated by Django 5.2.4 on 2025-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_criado_pedido_cupom_pedido_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AP', 'Aprovado'), ('CR', 'Criado'), ('RP', 'Reprovado'), ('PP', 'Pagamento pendente'), ('FP', 'Falha no Pagamento'), ('PR', 'Processando'), ('RE', 'Reembolsado'), ('CO', 'Concluido'), ('CA', 'Cancelado'), ('EN', 'Enviado'), ('FI', 'Finalizado')], default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total do pedido sem desconto', max_digits=10),
        ),
    ]
