# Generated by Django 5.2.4 on 2025-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_status_alter_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='payment_id_mercadopago',
            field=models.CharField(blank=True, help_text='ID do pagamento no MercadoPago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='ID do Payment Intent do Stripe', max_length=255, null=True),
        ),
    ]
